spring:
  profiles:
    group:
      "default": "local"
      "sandbox": ""
      "cbt": ""
      "prod": ""
  main:
    allow-bean-definition-overriding: true

server:
  shutdown: graceful
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /
    disable-swagger-default-url: true
    doc-expansion: none
    syntax-highlight:
      theme: nord
